export const GET_NEWS = "GET_NEWS"
export const GET_NEW = "GET_NEW"
export const POST_NEW = "ADD_NEW"
export const GET_SEARCH_NEWS = "GET_SEARCH_NEWS"
export const GET_CONTACT = "GET_CONTACT"
export const POST_CONTACT = "POST_CONTACT"
export const PUT_CONTACT = "PUT_CONTACT"
