// export const GET_NEWS = "GET_NEWS"
// export const GET_NEW = "GET_NEW"
// export const POST_NEW = "ADD_NEW"
// export const GET_SEARCH_NEWS = "GET_SEARCH_NEWS"
// export const GET_CONTACT = "GET_CONTACT"
// export const POST_CONTACT = "POST_CONTACT"
// export const PUT_CONTACT = "PUT_CONTACT"

export const LOAD_NEWS_START = "LOAD_NEWS_START"
export const LOAD_NEWS_SUCCESS = "LOAD_NEWS_SUCCESS"
export const LOAD_NEWS_ERROR = "LOAD_NEWS_ERROR"

export const GET_NEW_START = "GET_NEW_START"
export const GET_NEW_SUCCESS = "GET_NEW_SUCCESS"
export const GET_NEW_ERROR = "GET_NEW_ERROR"

export const GET_SEARCH_NEWS_START = "GET_SEARCH_NEWS_START"
export const GET_SEARCH_NEWS_SUCCESS = "GET_SEARCH_NEWS_SUCCESS"
export const GET_SEARCH_NEWS_ERROR = "GET_SEARCH_NEWS_ERROR"

